version: '3.3'

services:
  drupal:
    image: drupal:8-apache
    depends_on:
      - mysql
    ports:
      - 80:80
    restart: always
    volumes:
      # - ./html:/var/www/html
      # - ./html/modules:/var/www/html/modules
      # - ./html/profiles:/var/www/html/profiles
      # - ./html/themes:/var/www/html/themes
      - ./html/sites:/var/www/html/sites
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somedpupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysql
          - PMA_USER=root
          - PMA_PASSWORD=somedpupal
      restart: always
      ports:
          - 8080:80
      links:
          - mysql
volumes: 
  db_data: